//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientLibrairie.ServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CustomFault", Namespace="http://schemas.datacontract.org/2004/07/WcfLibrairie")]
    [System.SerializableAttribute()]
    public partial class CustomFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Affiliate", Namespace="http://schemas.datacontract.org/2004/07/BusinessObjects")]
    [System.SerializableAttribute()]
    public partial class Affiliate : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> BirthDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CardNumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> CardValidityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MainLibraryIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> BirthDate {
            get {
                return this.BirthDateField;
            }
            set {
                if ((this.BirthDateField.Equals(value) != true)) {
                    this.BirthDateField = value;
                    this.RaisePropertyChanged("BirthDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CardNum {
            get {
                return this.CardNumField;
            }
            set {
                if ((this.CardNumField.Equals(value) != true)) {
                    this.CardNumField = value;
                    this.RaisePropertyChanged("CardNum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> CardValidity {
            get {
                return this.CardValidityField;
            }
            set {
                if ((this.CardValidityField.Equals(value) != true)) {
                    this.CardValidityField = value;
                    this.RaisePropertyChanged("CardValidity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MainLibraryId {
            get {
                return this.MainLibraryIdField;
            }
            set {
                if ((this.MainLibraryIdField.Equals(value) != true)) {
                    this.MainLibraryIdField = value;
                    this.RaisePropertyChanged("MainLibraryId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Emprunt", Namespace="http://schemas.datacontract.org/2004/07/BusinessObjects")]
    [System.SerializableAttribute()]
    public partial class Emprunt : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CardNumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal DailyPenaltyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DurationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal FeeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ItemCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ItemIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime LastModifiedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LibraryIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LibraryNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ReturnDteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime StartDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TarifNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VolumeTitleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CardNum {
            get {
                return this.CardNumField;
            }
            set {
                if ((this.CardNumField.Equals(value) != true)) {
                    this.CardNumField = value;
                    this.RaisePropertyChanged("CardNum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal DailyPenalty {
            get {
                return this.DailyPenaltyField;
            }
            set {
                if ((this.DailyPenaltyField.Equals(value) != true)) {
                    this.DailyPenaltyField = value;
                    this.RaisePropertyChanged("DailyPenalty");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Duration {
            get {
                return this.DurationField;
            }
            set {
                if ((this.DurationField.Equals(value) != true)) {
                    this.DurationField = value;
                    this.RaisePropertyChanged("Duration");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Fee {
            get {
                return this.FeeField;
            }
            set {
                if ((this.FeeField.Equals(value) != true)) {
                    this.FeeField = value;
                    this.RaisePropertyChanged("Fee");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ItemCode {
            get {
                return this.ItemCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemCodeField, value) != true)) {
                    this.ItemCodeField = value;
                    this.RaisePropertyChanged("ItemCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ItemId {
            get {
                return this.ItemIdField;
            }
            set {
                if ((this.ItemIdField.Equals(value) != true)) {
                    this.ItemIdField = value;
                    this.RaisePropertyChanged("ItemId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime LastModified {
            get {
                return this.LastModifiedField;
            }
            set {
                if ((this.LastModifiedField.Equals(value) != true)) {
                    this.LastModifiedField = value;
                    this.RaisePropertyChanged("LastModified");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LibraryId {
            get {
                return this.LibraryIdField;
            }
            set {
                if ((this.LibraryIdField.Equals(value) != true)) {
                    this.LibraryIdField = value;
                    this.RaisePropertyChanged("LibraryId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LibraryName {
            get {
                return this.LibraryNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LibraryNameField, value) != true)) {
                    this.LibraryNameField = value;
                    this.RaisePropertyChanged("LibraryName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ReturnDte {
            get {
                return this.ReturnDteField;
            }
            set {
                if ((this.ReturnDteField.Equals(value) != true)) {
                    this.ReturnDteField = value;
                    this.RaisePropertyChanged("ReturnDte");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime StartDate {
            get {
                return this.StartDateField;
            }
            set {
                if ((this.StartDateField.Equals(value) != true)) {
                    this.StartDateField = value;
                    this.RaisePropertyChanged("StartDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TarifName {
            get {
                return this.TarifNameField;
            }
            set {
                if ((object.ReferenceEquals(this.TarifNameField, value) != true)) {
                    this.TarifNameField = value;
                    this.RaisePropertyChanged("TarifName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VolumeTitle {
            get {
                return this.VolumeTitleField;
            }
            set {
                if ((object.ReferenceEquals(this.VolumeTitleField, value) != true)) {
                    this.VolumeTitleField = value;
                    this.RaisePropertyChanged("VolumeTitle");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Library", Namespace="http://schemas.datacontract.org/2004/07/BusinessObjects")]
    [System.SerializableAttribute()]
    public partial class Library : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Item", Namespace="http://schemas.datacontract.org/2004/07/BusinessObjects")]
    [System.SerializableAttribute()]
    public partial class Item : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime BuyDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateEmpruntField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LibraryIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LocalisationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int VolumeIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime BuyDate {
            get {
                return this.BuyDateField;
            }
            set {
                if ((this.BuyDateField.Equals(value) != true)) {
                    this.BuyDateField = value;
                    this.RaisePropertyChanged("BuyDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateEmprunt {
            get {
                return this.DateEmpruntField;
            }
            set {
                if ((this.DateEmpruntField.Equals(value) != true)) {
                    this.DateEmpruntField = value;
                    this.RaisePropertyChanged("DateEmprunt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LibraryId {
            get {
                return this.LibraryIdField;
            }
            set {
                if ((this.LibraryIdField.Equals(value) != true)) {
                    this.LibraryIdField = value;
                    this.RaisePropertyChanged("LibraryId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Localisation {
            get {
                return this.LocalisationField;
            }
            set {
                if ((object.ReferenceEquals(this.LocalisationField, value) != true)) {
                    this.LocalisationField = value;
                    this.RaisePropertyChanged("Localisation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int VolumeId {
            get {
                return this.VolumeIdField;
            }
            set {
                if ((this.VolumeIdField.Equals(value) != true)) {
                    this.VolumeIdField = value;
                    this.RaisePropertyChanged("VolumeId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Volume", Namespace="http://schemas.datacontract.org/2004/07/BusinessObjects")]
    [System.SerializableAttribute()]
    public partial class Volume : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClientLibrairie.ServiceReference.Author[] AuthorsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CoverField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IsbnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClientLibrairie.ServiceReference.Author[] Authors {
            get {
                return this.AuthorsField;
            }
            set {
                if ((object.ReferenceEquals(this.AuthorsField, value) != true)) {
                    this.AuthorsField = value;
                    this.RaisePropertyChanged("Authors");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cover {
            get {
                return this.CoverField;
            }
            set {
                if ((object.ReferenceEquals(this.CoverField, value) != true)) {
                    this.CoverField = value;
                    this.RaisePropertyChanged("Cover");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Isbn {
            get {
                return this.IsbnField;
            }
            set {
                if ((object.ReferenceEquals(this.IsbnField, value) != true)) {
                    this.IsbnField = value;
                    this.RaisePropertyChanged("Isbn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Author", Namespace="http://schemas.datacontract.org/2004/07/BusinessObjects")]
    [System.SerializableAttribute()]
    public partial class Author : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PersIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PersId {
            get {
                return this.PersIdField;
            }
            set {
                if ((this.PersIdField.Equals(value) != true)) {
                    this.PersIdField = value;
                    this.RaisePropertyChanged("PersId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Tarif", Namespace="http://schemas.datacontract.org/2004/07/BusinessObjects")]
    [System.SerializableAttribute()]
    public partial class Tarif : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal DailyPenaltyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DurationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal FeeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LibraryIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int YearField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal DailyPenalty {
            get {
                return this.DailyPenaltyField;
            }
            set {
                if ((this.DailyPenaltyField.Equals(value) != true)) {
                    this.DailyPenaltyField = value;
                    this.RaisePropertyChanged("DailyPenalty");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Duration {
            get {
                return this.DurationField;
            }
            set {
                if ((this.DurationField.Equals(value) != true)) {
                    this.DurationField = value;
                    this.RaisePropertyChanged("Duration");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Fee {
            get {
                return this.FeeField;
            }
            set {
                if ((this.FeeField.Equals(value) != true)) {
                    this.FeeField = value;
                    this.RaisePropertyChanged("Fee");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LibraryId {
            get {
                return this.LibraryIdField;
            }
            set {
                if ((this.LibraryIdField.Equals(value) != true)) {
                    this.LibraryIdField = value;
                    this.RaisePropertyChanged("LibraryId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Year {
            get {
                return this.YearField;
            }
            set {
                if ((this.YearField.Equals(value) != true)) {
                    this.YearField = value;
                    this.RaisePropertyChanged("Year");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.IadminService")]
    public interface IadminService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IadminService/CheckIn", ReplyAction="http://tempuri.org/IadminService/CheckInResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ClientLibrairie.ServiceReference.CustomFault), Action="http://tempuri.org/IadminService/CheckInCustomFaultFault", Name="CustomFault", Namespace="http://schemas.datacontract.org/2004/07/WcfLibrairie")]
        bool CheckIn(string login, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IadminService/CheckIn", ReplyAction="http://tempuri.org/IadminService/CheckInResponse")]
        System.Threading.Tasks.Task<bool> CheckInAsync(string login, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IadminService/GetAffiliateById", ReplyAction="http://tempuri.org/IadminService/GetAffiliateByIdResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ClientLibrairie.ServiceReference.CustomFault), Action="http://tempuri.org/IadminService/GetAffiliateByIdCustomFaultFault", Name="CustomFault", Namespace="http://schemas.datacontract.org/2004/07/WcfLibrairie")]
        ClientLibrairie.ServiceReference.Affiliate GetAffiliateById(int lectId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IadminService/GetAffiliateById", ReplyAction="http://tempuri.org/IadminService/GetAffiliateByIdResponse")]
        System.Threading.Tasks.Task<ClientLibrairie.ServiceReference.Affiliate> GetAffiliateByIdAsync(int lectId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IadminService/GetAffiliateByName", ReplyAction="http://tempuri.org/IadminService/GetAffiliateByNameResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ClientLibrairie.ServiceReference.CustomFault), Action="http://tempuri.org/IadminService/GetAffiliateByNameCustomFaultFault", Name="CustomFault", Namespace="http://schemas.datacontract.org/2004/07/WcfLibrairie")]
        ClientLibrairie.ServiceReference.Affiliate GetAffiliateByName(string FirstName, string lastName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IadminService/GetAffiliateByName", ReplyAction="http://tempuri.org/IadminService/GetAffiliateByNameResponse")]
        System.Threading.Tasks.Task<ClientLibrairie.ServiceReference.Affiliate> GetAffiliateByNameAsync(string FirstName, string lastName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IadminService/GetEmpruntsByAffiliate", ReplyAction="http://tempuri.org/IadminService/GetEmpruntsByAffiliateResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ClientLibrairie.ServiceReference.CustomFault), Action="http://tempuri.org/IadminService/GetEmpruntsByAffiliateCustomFaultFault", Name="CustomFault", Namespace="http://schemas.datacontract.org/2004/07/WcfLibrairie")]
        ClientLibrairie.ServiceReference.Emprunt[] GetEmpruntsByAffiliate(int lectId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IadminService/GetEmpruntsByAffiliate", ReplyAction="http://tempuri.org/IadminService/GetEmpruntsByAffiliateResponse")]
        System.Threading.Tasks.Task<ClientLibrairie.ServiceReference.Emprunt[]> GetEmpruntsByAffiliateAsync(int lectId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IadminService/GetEmpruntByCode", ReplyAction="http://tempuri.org/IadminService/GetEmpruntByCodeResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ClientLibrairie.ServiceReference.CustomFault), Action="http://tempuri.org/IadminService/GetEmpruntByCodeCustomFaultFault", Name="CustomFault", Namespace="http://schemas.datacontract.org/2004/07/WcfLibrairie")]
        ClientLibrairie.ServiceReference.Emprunt GetEmpruntByCode(string code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IadminService/GetEmpruntByCode", ReplyAction="http://tempuri.org/IadminService/GetEmpruntByCodeResponse")]
        System.Threading.Tasks.Task<ClientLibrairie.ServiceReference.Emprunt> GetEmpruntByCodeAsync(string code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IadminService/GetRetards", ReplyAction="http://tempuri.org/IadminService/GetRetardsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ClientLibrairie.ServiceReference.CustomFault), Action="http://tempuri.org/IadminService/GetRetardsCustomFaultFault", Name="CustomFault", Namespace="http://schemas.datacontract.org/2004/07/WcfLibrairie")]
        ClientLibrairie.ServiceReference.Emprunt[] GetRetards(System.DateTime date, int libId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IadminService/GetRetards", ReplyAction="http://tempuri.org/IadminService/GetRetardsResponse")]
        System.Threading.Tasks.Task<ClientLibrairie.ServiceReference.Emprunt[]> GetRetardsAsync(System.DateTime date, int libId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IadminService/GetLibraries", ReplyAction="http://tempuri.org/IadminService/GetLibrariesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ClientLibrairie.ServiceReference.CustomFault), Action="http://tempuri.org/IadminService/GetLibrariesCustomFaultFault", Name="CustomFault", Namespace="http://schemas.datacontract.org/2004/07/WcfLibrairie")]
        ClientLibrairie.ServiceReference.Library[] GetLibraries();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IadminService/GetLibraries", ReplyAction="http://tempuri.org/IadminService/GetLibrariesResponse")]
        System.Threading.Tasks.Task<ClientLibrairie.ServiceReference.Library[]> GetLibrariesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IadminService/GetItemsByVolume", ReplyAction="http://tempuri.org/IadminService/GetItemsByVolumeResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ClientLibrairie.ServiceReference.CustomFault), Action="http://tempuri.org/IadminService/GetItemsByVolumeCustomFaultFault", Name="CustomFault", Namespace="http://schemas.datacontract.org/2004/07/WcfLibrairie")]
        ClientLibrairie.ServiceReference.Item[] GetItemsByVolume(int volumeId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IadminService/GetItemsByVolume", ReplyAction="http://tempuri.org/IadminService/GetItemsByVolumeResponse")]
        System.Threading.Tasks.Task<ClientLibrairie.ServiceReference.Item[]> GetItemsByVolumeAsync(int volumeId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IadminService/GetVolumeDetails", ReplyAction="http://tempuri.org/IadminService/GetVolumeDetailsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ClientLibrairie.ServiceReference.CustomFault), Action="http://tempuri.org/IadminService/GetVolumeDetailsCustomFaultFault", Name="CustomFault", Namespace="http://schemas.datacontract.org/2004/07/WcfLibrairie")]
        ClientLibrairie.ServiceReference.Volume GetVolumeDetails(int volumeId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IadminService/GetVolumeDetails", ReplyAction="http://tempuri.org/IadminService/GetVolumeDetailsResponse")]
        System.Threading.Tasks.Task<ClientLibrairie.ServiceReference.Volume> GetVolumeDetailsAsync(int volumeId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IadminService/GetVolumeDetailsByIsbn", ReplyAction="http://tempuri.org/IadminService/GetVolumeDetailsByIsbnResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ClientLibrairie.ServiceReference.CustomFault), Action="http://tempuri.org/IadminService/GetVolumeDetailsByIsbnCustomFaultFault", Name="CustomFault", Namespace="http://schemas.datacontract.org/2004/07/WcfLibrairie")]
        ClientLibrairie.ServiceReference.Volume GetVolumeDetailsByIsbn(string isbn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IadminService/GetVolumeDetailsByIsbn", ReplyAction="http://tempuri.org/IadminService/GetVolumeDetailsByIsbnResponse")]
        System.Threading.Tasks.Task<ClientLibrairie.ServiceReference.Volume> GetVolumeDetailsByIsbnAsync(string isbn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IadminService/GetVolumeByTitle", ReplyAction="http://tempuri.org/IadminService/GetVolumeByTitleResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ClientLibrairie.ServiceReference.CustomFault), Action="http://tempuri.org/IadminService/GetVolumeByTitleCustomFaultFault", Name="CustomFault", Namespace="http://schemas.datacontract.org/2004/07/WcfLibrairie")]
        ClientLibrairie.ServiceReference.Volume GetVolumeByTitle(string titleLike);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IadminService/GetVolumeByTitle", ReplyAction="http://tempuri.org/IadminService/GetVolumeByTitleResponse")]
        System.Threading.Tasks.Task<ClientLibrairie.ServiceReference.Volume> GetVolumeByTitleAsync(string titleLike);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IadminService/GetVolumesByTitle", ReplyAction="http://tempuri.org/IadminService/GetVolumesByTitleResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ClientLibrairie.ServiceReference.CustomFault), Action="http://tempuri.org/IadminService/GetVolumesByTitleCustomFaultFault", Name="CustomFault", Namespace="http://schemas.datacontract.org/2004/07/WcfLibrairie")]
        ClientLibrairie.ServiceReference.Volume[] GetVolumesByTitle(string titleLike);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IadminService/GetVolumesByTitle", ReplyAction="http://tempuri.org/IadminService/GetVolumesByTitleResponse")]
        System.Threading.Tasks.Task<ClientLibrairie.ServiceReference.Volume[]> GetVolumesByTitleAsync(string titleLike);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IadminService/GetTarifsByLib", ReplyAction="http://tempuri.org/IadminService/GetTarifsByLibResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ClientLibrairie.ServiceReference.CustomFault), Action="http://tempuri.org/IadminService/GetTarifsByLibCustomFaultFault", Name="CustomFault", Namespace="http://schemas.datacontract.org/2004/07/WcfLibrairie")]
        ClientLibrairie.ServiceReference.Tarif[] GetTarifsByLib(int libraryId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IadminService/GetTarifsByLib", ReplyAction="http://tempuri.org/IadminService/GetTarifsByLibResponse")]
        System.Threading.Tasks.Task<ClientLibrairie.ServiceReference.Tarif[]> GetTarifsByLibAsync(int libraryId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IadminService/GetAllAuthorsNames", ReplyAction="http://tempuri.org/IadminService/GetAllAuthorsNamesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ClientLibrairie.ServiceReference.CustomFault), Action="http://tempuri.org/IadminService/GetAllAuthorsNamesCustomFaultFault", Name="CustomFault", Namespace="http://schemas.datacontract.org/2004/07/WcfLibrairie")]
        ClientLibrairie.ServiceReference.Author[] GetAllAuthorsNames();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IadminService/GetAllAuthorsNames", ReplyAction="http://tempuri.org/IadminService/GetAllAuthorsNamesResponse")]
        System.Threading.Tasks.Task<ClientLibrairie.ServiceReference.Author[]> GetAllAuthorsNamesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IadminService/AddVolume", ReplyAction="http://tempuri.org/IadminService/AddVolumeResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ClientLibrairie.ServiceReference.CustomFault), Action="http://tempuri.org/IadminService/AddVolumeCustomFaultFault", Name="CustomFault", Namespace="http://schemas.datacontract.org/2004/07/WcfLibrairie")]
        void AddVolume(ClientLibrairie.ServiceReference.Volume volumeToAdd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IadminService/AddVolume", ReplyAction="http://tempuri.org/IadminService/AddVolumeResponse")]
        System.Threading.Tasks.Task AddVolumeAsync(ClientLibrairie.ServiceReference.Volume volumeToAdd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IadminService/UpdateVolume", ReplyAction="http://tempuri.org/IadminService/UpdateVolumeResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ClientLibrairie.ServiceReference.CustomFault), Action="http://tempuri.org/IadminService/UpdateVolumeCustomFaultFault", Name="CustomFault", Namespace="http://schemas.datacontract.org/2004/07/WcfLibrairie")]
        void UpdateVolume(ClientLibrairie.ServiceReference.Volume volumeToUpdate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IadminService/UpdateVolume", ReplyAction="http://tempuri.org/IadminService/UpdateVolumeResponse")]
        System.Threading.Tasks.Task UpdateVolumeAsync(ClientLibrairie.ServiceReference.Volume volumeToUpdate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IadminService/DeleteVolume", ReplyAction="http://tempuri.org/IadminService/DeleteVolumeResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ClientLibrairie.ServiceReference.CustomFault), Action="http://tempuri.org/IadminService/DeleteVolumeCustomFaultFault", Name="CustomFault", Namespace="http://schemas.datacontract.org/2004/07/WcfLibrairie")]
        void DeleteVolume(ClientLibrairie.ServiceReference.Volume volumeToDelete);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IadminService/DeleteVolume", ReplyAction="http://tempuri.org/IadminService/DeleteVolumeResponse")]
        System.Threading.Tasks.Task DeleteVolumeAsync(ClientLibrairie.ServiceReference.Volume volumeToDelete);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IadminService/AddItem", ReplyAction="http://tempuri.org/IadminService/AddItemResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ClientLibrairie.ServiceReference.CustomFault), Action="http://tempuri.org/IadminService/AddItemCustomFaultFault", Name="CustomFault", Namespace="http://schemas.datacontract.org/2004/07/WcfLibrairie")]
        void AddItem(ClientLibrairie.ServiceReference.Item itemToAdd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IadminService/AddItem", ReplyAction="http://tempuri.org/IadminService/AddItemResponse")]
        System.Threading.Tasks.Task AddItemAsync(ClientLibrairie.ServiceReference.Item itemToAdd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IadminService/UpdateItem", ReplyAction="http://tempuri.org/IadminService/UpdateItemResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ClientLibrairie.ServiceReference.CustomFault), Action="http://tempuri.org/IadminService/UpdateItemCustomFaultFault", Name="CustomFault", Namespace="http://schemas.datacontract.org/2004/07/WcfLibrairie")]
        void UpdateItem(ClientLibrairie.ServiceReference.Item itemToUpdate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IadminService/UpdateItem", ReplyAction="http://tempuri.org/IadminService/UpdateItemResponse")]
        System.Threading.Tasks.Task UpdateItemAsync(ClientLibrairie.ServiceReference.Item itemToUpdate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IadminService/DeleteItem", ReplyAction="http://tempuri.org/IadminService/DeleteItemResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ClientLibrairie.ServiceReference.CustomFault), Action="http://tempuri.org/IadminService/DeleteItemCustomFaultFault", Name="CustomFault", Namespace="http://schemas.datacontract.org/2004/07/WcfLibrairie")]
        void DeleteItem(ClientLibrairie.ServiceReference.Item itemToDelete);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IadminService/DeleteItem", ReplyAction="http://tempuri.org/IadminService/DeleteItemResponse")]
        System.Threading.Tasks.Task DeleteItemAsync(ClientLibrairie.ServiceReference.Item itemToDelete);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IadminService/CloseEmprunt", ReplyAction="http://tempuri.org/IadminService/CloseEmpruntResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ClientLibrairie.ServiceReference.CustomFault), Action="http://tempuri.org/IadminService/CloseEmpruntCustomFaultFault", Name="CustomFault", Namespace="http://schemas.datacontract.org/2004/07/WcfLibrairie")]
        void CloseEmprunt(int EmpruntToCloseID, System.DateTime LastModified);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IadminService/CloseEmprunt", ReplyAction="http://tempuri.org/IadminService/CloseEmpruntResponse")]
        System.Threading.Tasks.Task CloseEmpruntAsync(int EmpruntToCloseID, System.DateTime LastModified);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IadminServiceChannel : ClientLibrairie.ServiceReference.IadminService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IadminServiceClient : System.ServiceModel.ClientBase<ClientLibrairie.ServiceReference.IadminService>, ClientLibrairie.ServiceReference.IadminService {
        
        public IadminServiceClient() {
        }
        
        public IadminServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IadminServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IadminServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IadminServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool CheckIn(string login, string password) {
            return base.Channel.CheckIn(login, password);
        }
        
        public System.Threading.Tasks.Task<bool> CheckInAsync(string login, string password) {
            return base.Channel.CheckInAsync(login, password);
        }
        
        public ClientLibrairie.ServiceReference.Affiliate GetAffiliateById(int lectId) {
            return base.Channel.GetAffiliateById(lectId);
        }
        
        public System.Threading.Tasks.Task<ClientLibrairie.ServiceReference.Affiliate> GetAffiliateByIdAsync(int lectId) {
            return base.Channel.GetAffiliateByIdAsync(lectId);
        }
        
        public ClientLibrairie.ServiceReference.Affiliate GetAffiliateByName(string FirstName, string lastName) {
            return base.Channel.GetAffiliateByName(FirstName, lastName);
        }
        
        public System.Threading.Tasks.Task<ClientLibrairie.ServiceReference.Affiliate> GetAffiliateByNameAsync(string FirstName, string lastName) {
            return base.Channel.GetAffiliateByNameAsync(FirstName, lastName);
        }
        
        public ClientLibrairie.ServiceReference.Emprunt[] GetEmpruntsByAffiliate(int lectId) {
            return base.Channel.GetEmpruntsByAffiliate(lectId);
        }
        
        public System.Threading.Tasks.Task<ClientLibrairie.ServiceReference.Emprunt[]> GetEmpruntsByAffiliateAsync(int lectId) {
            return base.Channel.GetEmpruntsByAffiliateAsync(lectId);
        }
        
        public ClientLibrairie.ServiceReference.Emprunt GetEmpruntByCode(string code) {
            return base.Channel.GetEmpruntByCode(code);
        }
        
        public System.Threading.Tasks.Task<ClientLibrairie.ServiceReference.Emprunt> GetEmpruntByCodeAsync(string code) {
            return base.Channel.GetEmpruntByCodeAsync(code);
        }
        
        public ClientLibrairie.ServiceReference.Emprunt[] GetRetards(System.DateTime date, int libId) {
            return base.Channel.GetRetards(date, libId);
        }
        
        public System.Threading.Tasks.Task<ClientLibrairie.ServiceReference.Emprunt[]> GetRetardsAsync(System.DateTime date, int libId) {
            return base.Channel.GetRetardsAsync(date, libId);
        }
        
        public ClientLibrairie.ServiceReference.Library[] GetLibraries() {
            return base.Channel.GetLibraries();
        }
        
        public System.Threading.Tasks.Task<ClientLibrairie.ServiceReference.Library[]> GetLibrariesAsync() {
            return base.Channel.GetLibrariesAsync();
        }
        
        public ClientLibrairie.ServiceReference.Item[] GetItemsByVolume(int volumeId) {
            return base.Channel.GetItemsByVolume(volumeId);
        }
        
        public System.Threading.Tasks.Task<ClientLibrairie.ServiceReference.Item[]> GetItemsByVolumeAsync(int volumeId) {
            return base.Channel.GetItemsByVolumeAsync(volumeId);
        }
        
        public ClientLibrairie.ServiceReference.Volume GetVolumeDetails(int volumeId) {
            return base.Channel.GetVolumeDetails(volumeId);
        }
        
        public System.Threading.Tasks.Task<ClientLibrairie.ServiceReference.Volume> GetVolumeDetailsAsync(int volumeId) {
            return base.Channel.GetVolumeDetailsAsync(volumeId);
        }
        
        public ClientLibrairie.ServiceReference.Volume GetVolumeDetailsByIsbn(string isbn) {
            return base.Channel.GetVolumeDetailsByIsbn(isbn);
        }
        
        public System.Threading.Tasks.Task<ClientLibrairie.ServiceReference.Volume> GetVolumeDetailsByIsbnAsync(string isbn) {
            return base.Channel.GetVolumeDetailsByIsbnAsync(isbn);
        }
        
        public ClientLibrairie.ServiceReference.Volume GetVolumeByTitle(string titleLike) {
            return base.Channel.GetVolumeByTitle(titleLike);
        }
        
        public System.Threading.Tasks.Task<ClientLibrairie.ServiceReference.Volume> GetVolumeByTitleAsync(string titleLike) {
            return base.Channel.GetVolumeByTitleAsync(titleLike);
        }
        
        public ClientLibrairie.ServiceReference.Volume[] GetVolumesByTitle(string titleLike) {
            return base.Channel.GetVolumesByTitle(titleLike);
        }
        
        public System.Threading.Tasks.Task<ClientLibrairie.ServiceReference.Volume[]> GetVolumesByTitleAsync(string titleLike) {
            return base.Channel.GetVolumesByTitleAsync(titleLike);
        }
        
        public ClientLibrairie.ServiceReference.Tarif[] GetTarifsByLib(int libraryId) {
            return base.Channel.GetTarifsByLib(libraryId);
        }
        
        public System.Threading.Tasks.Task<ClientLibrairie.ServiceReference.Tarif[]> GetTarifsByLibAsync(int libraryId) {
            return base.Channel.GetTarifsByLibAsync(libraryId);
        }
        
        public ClientLibrairie.ServiceReference.Author[] GetAllAuthorsNames() {
            return base.Channel.GetAllAuthorsNames();
        }
        
        public System.Threading.Tasks.Task<ClientLibrairie.ServiceReference.Author[]> GetAllAuthorsNamesAsync() {
            return base.Channel.GetAllAuthorsNamesAsync();
        }
        
        public void AddVolume(ClientLibrairie.ServiceReference.Volume volumeToAdd) {
            base.Channel.AddVolume(volumeToAdd);
        }
        
        public System.Threading.Tasks.Task AddVolumeAsync(ClientLibrairie.ServiceReference.Volume volumeToAdd) {
            return base.Channel.AddVolumeAsync(volumeToAdd);
        }
        
        public void UpdateVolume(ClientLibrairie.ServiceReference.Volume volumeToUpdate) {
            base.Channel.UpdateVolume(volumeToUpdate);
        }
        
        public System.Threading.Tasks.Task UpdateVolumeAsync(ClientLibrairie.ServiceReference.Volume volumeToUpdate) {
            return base.Channel.UpdateVolumeAsync(volumeToUpdate);
        }
        
        public void DeleteVolume(ClientLibrairie.ServiceReference.Volume volumeToDelete) {
            base.Channel.DeleteVolume(volumeToDelete);
        }
        
        public System.Threading.Tasks.Task DeleteVolumeAsync(ClientLibrairie.ServiceReference.Volume volumeToDelete) {
            return base.Channel.DeleteVolumeAsync(volumeToDelete);
        }
        
        public void AddItem(ClientLibrairie.ServiceReference.Item itemToAdd) {
            base.Channel.AddItem(itemToAdd);
        }
        
        public System.Threading.Tasks.Task AddItemAsync(ClientLibrairie.ServiceReference.Item itemToAdd) {
            return base.Channel.AddItemAsync(itemToAdd);
        }
        
        public void UpdateItem(ClientLibrairie.ServiceReference.Item itemToUpdate) {
            base.Channel.UpdateItem(itemToUpdate);
        }
        
        public System.Threading.Tasks.Task UpdateItemAsync(ClientLibrairie.ServiceReference.Item itemToUpdate) {
            return base.Channel.UpdateItemAsync(itemToUpdate);
        }
        
        public void DeleteItem(ClientLibrairie.ServiceReference.Item itemToDelete) {
            base.Channel.DeleteItem(itemToDelete);
        }
        
        public System.Threading.Tasks.Task DeleteItemAsync(ClientLibrairie.ServiceReference.Item itemToDelete) {
            return base.Channel.DeleteItemAsync(itemToDelete);
        }
        
        public void CloseEmprunt(int EmpruntToCloseID, System.DateTime LastModified) {
            base.Channel.CloseEmprunt(EmpruntToCloseID, LastModified);
        }
        
        public System.Threading.Tasks.Task CloseEmpruntAsync(int EmpruntToCloseID, System.DateTime LastModified) {
            return base.Channel.CloseEmpruntAsync(EmpruntToCloseID, LastModified);
        }
    }
}
