//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfBLAffiliate
{
    using System;
    using System.Collections.Generic;
    
    public partial class vLibrary
    {
        public int IdLibrary { get; set; }
        public string NameLibrary { get; set; }
        public string CodeIdLibrary { get; set; }
    }
}
