//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfBLAffiliate
{
    using System;
    using System.Collections.Generic;
    
    public partial class vWishlist
    {
        public int Id { get; set; }
        public int CardNum { get; set; }
        public int Volume_Id { get; set; }
        public string Isbn { get; set; }
        public string Title { get; set; }
        public string Cover { get; set; }
    }
}
